# Site settings
title: Telekom Innovation Laboratories
email: your-email@domain.com
url: https://TelekomLabs.github.io
description: "Telekom Innovation Laboratories (T-Labs) are the central research and development unit of Deutsche Telekom AG"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e20074
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Deutsche Telekom Laboratroies
  location: Berlin
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/T_Labs
  - title: google-plus
    url: http://www.google.com/+tlabs
  - title: youtube
    url: https://www.youtube.com/user/TelekomInnovation
  - title: github
    url: https://github.com/TelekomLabs

# Postal address (add as many lines as necessary)
address:
  - line: Ernst-Reuter-Platz 7
  - line: 10587 Berlin, Deutschland

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
